apiVersion: example.com/v1
kind: SecretCertificate
metadata:
  name: example-secret-certificate
spec:
  vaultServer: "https://your-vault-url"
  vaultToken: "your-vault-token"
  vaultSecretPath: "/v1/certs/data/svc-dev.ink"
  secretName: "example-tls-secret"
  namespace: "your-namespace"
