# templates/crds/secretcertificate_crd.yaml

{{- $CRDName := "secretcertificates.example.com" -}}
{{- $CRDValue := .Files.Get "crds/secret_certificate_crd.yaml" | toYaml | nindent 4 -}}

{{- if .Files.Has "crds/secret_certificate_crd.yaml" -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ $CRDName }}
spec:
  group: example.com
  names:
    kind: SecretCertificate
    listKind: SecretCertificateList
    plural: secretcertificates
    singular: secretcertificate
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              vaultServer:
                type: string
              vaultToken:
                type: string
              vaultSecretPath:
                type: string
              secretName:
                type: string
              namespace:
                type: string
{{- end }}
